package hu.bme.mit.theta.xta.learning.compositional.common;

import de.learnlib.sul.SULMapper;

import hu.bme.mit.theta.xta.Guard;
import hu.bme.mit.theta.xta.Update;
import hu.bme.mit.theta.xta.XtaProcess;
import hu.bme.mit.theta.xta.XtaSystem;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import java.util.function.Function;

/**
 * A mapper that translates abstract string symbols from the learning algorithm
 * into concrete timing constraints ({@link TransitionConstraints}) for the T' SUL.
 * During initialization, it iterates through all edges in the provided {@link XtaSystem},
 * extracts their clock guards and clock updates, and builds a dictionary using
 * unique edge names (e.g., "Process_Source->Target") as keys.
 *
 * @param <AO> The abstract output type for LearnLib.
 * @param <CO> The concrete output type from the SUL.
 */
public class XtaTimingMapper<AO, CO> implements SULMapper<String, AO, TransitionConstraints, CO> {
    private final Map<String, TransitionConstraints> transitionConstraints;
    private final Function<CO, AO> outputFunction;

    private XtaTimingMapper(XtaSystem xtaSystem, Function<CO, AO> outputFunction) {
        this.transitionConstraints = new HashMap<>();
        this.outputFunction = outputFunction;

        for (XtaProcess process : xtaSystem.getProcesses()) {
            for (var edge : process.getEdges()) {
                if (!isTimingRelevant(edge)) continue;

                List<Guard.ClockGuard> clockGuards = getClockGuardsForEdge(edge);
                List<Update> clockResets = getClockUpdatesForEdge(edge);
                List<Guard.ClockGuard> sourceInvs = getClockInvariantsForLoc(edge.getSource());
                List<Guard.ClockGuard> targetInvs = getClockInvariantsForLoc(edge.getTarget());

                TransitionConstraints constraints = TransitionConstraints.create(clockGuards, clockResets, sourceInvs, targetInvs);
                String edgeName = generateSymbolForEdge(edge);
                transitionConstraints.put(edgeName, constraints);
            }
        }
    }

    /**
     * Creates a new mapper by extracting timing information from all edges in the system.
     *
     * @param xtaSystem      The timed automaton system to extract edges from.
     * @param outputFunction A function to map the concrete SUL output back to an abstract output.
     * @return A new initialized XtaTimingMapper.
     */
    public static <AO, CO> XtaTimingMapper<AO, CO> create(XtaSystem xtaSystem, Function<CO, AO> outputFunction) {
        return new XtaTimingMapper<>(xtaSystem, outputFunction);
    }

    /**
     * Translates an abstract input string (edge name) into its corresponding timing data.
     *
     * @param abstractInput The name of the edge (e.g., "P1_wait->cs").
     * @return The {@link TransitionConstraints} containing the clock guards and resets for the edge.
     */
    @Override
    public TransitionConstraints mapInput(String abstractInput) {
        return transitionConstraints.get(abstractInput);
    }

    /**
     * Translates the concrete output from the SUL back to the abstract output for LearnLib.
     *
     * @param concreteOutput The output generated by the SUL.
     * @return The mapped abstract output.
     */
    @Override
    public AO mapOutput(CO concreteOutput) {
        return outputFunction.apply(concreteOutput);
    }

    /**
     * Returns the set of all valid abstract input symbols extracted from the system.
     * This serves as the input alphabet for the LearnLib learning algorithm.
     *
     * @return A set of string representations of the system's edges.
     */
    public Set<String> getAlphabet() {
        return transitionConstraints.keySet();
    }

    /**
     * Generates a unique string symbol for the given edge, used as the abstract
     * input alphabet symbol in the learning algorithm.
     * The symbol encodes the source and target location names, disambiguated by
     * the edge's identity hash to handle parallel edges between the same locations.
     *
     * @param edge The timed automaton edge to generate a symbol for.
     * @return A unique string of the form {@code "Source->Target_<hash>"}.
     */
    public static String generateSymbolForEdge(XtaProcess.Edge edge) {
        if (edge.getSync().isPresent()) {
            return edge.getSync().get().getLabel().getName();
        }
        return edge.getSource().getName() + "->" + edge.getTarget().getName();
    }

    /**
     * @param edge The timed automaton edge.
     * @return The list of clock guards.
     */
    private List<Guard.ClockGuard> getClockGuardsForEdge(XtaProcess.Edge edge) {
        List<Guard.ClockGuard> clockGuards = new ArrayList<>();

        for (Guard guard : edge.getGuards()) {
            if (guard.isClockGuard()) {
                clockGuards.add(guard.asClockGuard());
            }
        }
        return clockGuards;
    }

    /**
     * @param edge The timed automaton edge.
     * @return The list of clock updates (resets).
     */
    private List<Update> getClockUpdatesForEdge(XtaProcess.Edge edge) {
        List<Update> clockUpdates = new ArrayList<>();

        for (Update update : edge.getUpdates()) {
            if (update.isClockUpdate()) {
                clockUpdates.add(update.asClockUpdate());
            }
        }
        return clockUpdates;
    }

    /**
     * @param loc The timed automaton location.
     * @return The list of location invariants.
     */
    private List<Guard.ClockGuard> getClockInvariantsForLoc(XtaProcess.Loc loc) {
        List<Guard.ClockGuard> clockInvariants = new ArrayList<>();

        for (Guard guard : loc.getInvars()) {
            if (guard.isClockGuard()) {
                clockInvariants.add(guard.asClockGuard());
            }
        }

        return clockInvariants;
    }

    /**
     * Returns true if the edge has any timing-relevant constraints: clock guards,
     * clock resets, or differing source and target invariants.
     * Edges without any timing information are excluded from the mapper's alphabet,
     * as they carry no constraints for the T' SUL.
     */
    private static boolean isTimingRelevant(XtaProcess.Edge edge) {
        for (Guard g : edge.getGuards()) {
            if (g.isClockGuard()) return true;
        }
        for (Update u : edge.getUpdates()) {
            if (u.isClockUpdate()) return true;
        }
        List<Guard> srcInvs = edge.getSource().getInvars().stream()
                .filter(Guard::isClockGuard).toList();
        List<Guard> tgtInvs = edge.getTarget().getInvars().stream()
                .filter(Guard::isClockGuard).toList();
        return !srcInvs.equals(tgtInvs);
    }
}