package hu.bme.mit.theta.xta.learning.compositional.modelchecking;

import hu.bme.mit.theta.analysis.Prec;
import hu.bme.mit.theta.analysis.expl.ExplPrec;
import hu.bme.mit.theta.analysis.expl.ItpRefToExplPrec;
import hu.bme.mit.theta.analysis.expl.VarsRefToExplPrec;
import hu.bme.mit.theta.analysis.expr.refinement.*;
import hu.bme.mit.theta.core.type.Expr;
import hu.bme.mit.theta.core.type.booltype.BoolType;
import hu.bme.mit.theta.solver.ItpSolver;
import hu.bme.mit.theta.solver.UCSolver;

/**
 * A configuration bundle that pairs an {@link ExprTraceChecker} with a corresponding
 * {@link RefutationToPrec} strategy.
 * <p>
 * In the learning-based compositional model checking framework's discrete CEGAR phase
 * ({@code A || H}), verifying the feasibility of abstract counterexamples requires evaluating
 * an SMT trace. If the trace is spurious, the resulting refutation (e.g., interpolants
 * or unsat cores) must be converted into a new precision to refine the abstraction.
 * This interface neatly encapsulates both components of that refinement step.
 * <p>
 * The generic parameter {@code P} allows this strategy to work with arbitrary precision
 * types (e.g., a pure {@link ExplPrec} or a combined {@code Prod2Prec}). The interface
 * also provides several static convenience factories for standard explicit-state
 * ({@code ExplPrec}) refinement strategies.
 *
 * @param <P> The precision type (e.g., {@code ExplPrec} or {@code Prod2Prec<ExplPrec, ZonePrec>}).
 * @param <R> The refutation type generated by the trace checker (e.g., {@code ItpRefutation}).
 */
public interface TraceCheckerStrategy<P extends Prec, R extends Refutation> {

    /**
     * @return The trace checker responsible for SMT-based feasibility analysis of counterexamples.
     */
    ExprTraceChecker<R> checker();

    /**
     * @return The strategy used to extract a new precision from a generated refutation.
     */
    RefutationToPrec<P, R> refToPrec();

    /**
     * General factory method to bundle a custom trace checker and a precision extractor.
     *
     * @param checker   The SMT-based trace checker.
     * @param refToPrec The precision extraction strategy.
     * @param <P>       The precision type.
     * @param <R>       The refutation type.
     * @return A new {@link TraceCheckerStrategy} instance.
     */
    static <P extends Prec, R extends Refutation> TraceCheckerStrategy<P, R> of(
            ExprTraceChecker<R> checker,
            RefutationToPrec<P, R> refToPrec
    ) {
        return new TraceCheckerStrategy<>() {
            @Override public ExprTraceChecker<R> checker() { return checker; }
            @Override public RefutationToPrec<P, R> refToPrec() { return refToPrec; }
        };
    }

    /**
     * Creates a strategy based on Sequence Interpolation (SeqItp).
     *
     * @param init   The initial logical state expression.
     * @param target The target (unsafe) logical state expression.
     * @param solver The interpolating SMT solver.
     * @return A strategy yielding {@link ExplPrec} via sequence interpolants.
     */
    static TraceCheckerStrategy<ExplPrec, ItpRefutation> seqItp(
            Expr<BoolType> init, Expr<BoolType> target, ItpSolver solver
    ) {
        return of(ExprTraceSeqItpChecker.create(init, target, solver), new ItpRefToExplPrec());
    }

    /**
     * Creates a strategy based on Forward Binary Interpolation (FwBinItp).
     *
     * @param init   The initial logical state expression.
     * @param target The target (unsafe) logical state expression.
     * @param solver The interpolating SMT solver.
     * @return A strategy yielding {@link ExplPrec} via forward binary interpolants.
     */
    static TraceCheckerStrategy<ExplPrec, ItpRefutation> fwBinItp(
            Expr<BoolType> init, Expr<BoolType> target, ItpSolver solver
    ) {
        return of(ExprTraceFwBinItpChecker.create(init, target, solver), new ItpRefToExplPrec());
    }

    /**
     * Creates a strategy based on Backward Binary Interpolation (BwBinItp).
     *
     * @param init   The initial logical state expression.
     * @param target The target (unsafe) logical state expression.
     * @param solver The interpolating SMT solver.
     * @return A strategy yielding {@link ExplPrec} via backward binary interpolants.
     */
    static TraceCheckerStrategy<ExplPrec, ItpRefutation> bwBinItp(
            Expr<BoolType> init, Expr<BoolType> target, ItpSolver solver
    ) {
        return of(ExprTraceBwBinItpChecker.create(init, target, solver), new ItpRefToExplPrec());
    }

    /**
     * Creates a strategy based on Unsat Core extraction (identifying conflicting variables).
     *
     * @param init   The initial logical state expression.
     * @param target The target (unsafe) logical state expression.
     * @param solver The unsat-core-capable SMT solver.
     * @return A strategy yielding {@link ExplPrec} via unsat core extraction.
     */
    static TraceCheckerStrategy<ExplPrec, VarsRefutation> unsatCore(
            Expr<BoolType> init, Expr<BoolType> target, UCSolver solver
    ) {
        return of(ExprTraceUnsatCoreChecker.create(init, target, solver), new VarsRefToExplPrec());
    }

    /**
     * Creates a combined strategy from two underlying trace checkers.
     *
     * @param checker1  The primary trace checker.
     * @param checker2  The secondary trace checker.
     * @param merger    The logic defining how the statuses of both checkers are merged.
     * @param refToPrec The precision extraction strategy for the resulting refutation.
     * @param <R>       The refutation type.
     * @return A combined {@link TraceCheckerStrategy}.
     */
    static <R extends Refutation> TraceCheckerStrategy<ExplPrec, R> combined(
            ExprTraceChecker<R> checker1,
            ExprTraceChecker<R> checker2,
            ExprTraceStatusMerger<R> merger,
            RefutationToPrec<ExplPrec, R> refToPrec
    ) {
        return of(ExprTraceCombinedChecker.create(checker1, checker2, merger), refToPrec);
    }
}