package hu.bme.mit.theta.xta.learning.compositional.realizability;

import hu.bme.mit.theta.analysis.InitFunc;
import hu.bme.mit.theta.analysis.Prec;
import hu.bme.mit.theta.analysis.State;
import hu.bme.mit.theta.xta.analysis.XtaState;

import net.automatalib.automaton.fsa.DFA;

import java.util.ArrayList;
import java.util.Collection;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Initial state function for the discrete finite-state model checking phase.
 * <p>
 * In the learning-based compositional model checking framework, this class computes
 * the initial states for the parallel composition {@code A || H}, where {@code A} is
 * the purely discrete abstraction of the timed system, and {@code H} is the product
 * DFA representing the learned hypothesis.
 * <p>
 * The composite initial states are generated by pairing each valid initial state of the
 * inner discrete system ({@link XtaState}) with the single initial state of the
 * product DFA. Since this operates strictly in the discrete domain, no clock
 * initializations or delay (up) operations are performed here.
 *
 * @param <S>     The inner data state type of the XTA (e.g., {@code ExplState}).
 * @param <prodS> The state type of the product DFA (representing the learned hypothesis).
 * @param <P>     The precision type used by the underlying discrete analysis.
 */
public class DiscreteCompositionInitFunc<S extends State, prodS, P extends Prec>
        implements InitFunc<DiscreteCompositionState<S, prodS>, P> {

    private final InitFunc<XtaState<S>, P> innerInitFunc;
    private final DFA<prodS, String> productDfa;

    private DiscreteCompositionInitFunc(InitFunc<XtaState<S>, P> innerInitFunc,
                                        DFA<prodS, String> productDfa) {
        this.innerInitFunc = checkNotNull(innerInitFunc);
        this.productDfa = checkNotNull(productDfa);
    }

    /**
     * Creates a new {@link DiscreteCompositionInitFunc}.
     *
     * @param innerInitFunc The initialization function for the inner discrete XTA states.
     * @param hypothesis    The product DFA representing the learned hypothesis {@code H}.
     * @param <S>           The inner data state type.
     * @param <prodS>       The state type of the product DFA.
     * @param <P>           The precision type.
     * @return A new {@link DiscreteCompositionInitFunc} instance.
     */
    public static <S extends State, prodS, P extends Prec> DiscreteCompositionInitFunc<S, prodS, P> create(
            InitFunc<XtaState<S>, P> innerInitFunc, DFA<prodS, String> hypothesis) {
        return new DiscreteCompositionInitFunc<>(innerInitFunc, hypothesis);
    }

    @Override
    public Collection<DiscreteCompositionState<S, prodS>> getInitStates(P prec) {
        prodS dfaInitState = productDfa.getInitialState();
        Collection<? extends XtaState<S>> xtaInitStates = innerInitFunc.getInitStates(prec);

        Collection<DiscreteCompositionState<S, prodS>> result = new ArrayList<>();
        for (XtaState<S> xtaInitState : xtaInitStates) {
            result.add(DiscreteCompositionState.create(xtaInitState, dfaInitState));
        }
        return result;
    }
}
