package hu.bme.mit.theta.xta.learning.compositional.realizability;

import hu.bme.mit.theta.analysis.Prec;
import hu.bme.mit.theta.analysis.State;
import hu.bme.mit.theta.analysis.Trace;
import hu.bme.mit.theta.analysis.algorithm.ARG;
import hu.bme.mit.theta.analysis.algorithm.ArgNode;
import hu.bme.mit.theta.analysis.algorithm.ArgTrace;
import hu.bme.mit.theta.analysis.algorithm.cegar.Refiner;
import hu.bme.mit.theta.analysis.algorithm.cegar.RefinerResult;
import hu.bme.mit.theta.analysis.expr.ExprState;
import hu.bme.mit.theta.analysis.expr.refinement.*;
import hu.bme.mit.theta.xta.analysis.XtaAction;
import hu.bme.mit.theta.xta.analysis.XtaState;

import java.util.List;
import java.util.stream.Collectors;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Refiner implementation for the discrete finite-state model checking phase.
 * <p>
 * In the learning-based compositional model checking framework, this class is part
 * of the CEGAR loop used to verify the safety of the parallel composition {@code A || H}.
 * When the abstractor finds a counterexample path in the composite state space, this
 * refiner checks if the path is logically feasible.
 * <p>
 * Because the hypothesis DFA {@code H} only restricts the sequence of actions (labels),
 * the logical feasibility of the data variables along the path depends entirely on the
 * underlying {@link XtaState} sequence. Thus, the refiner projects the composite trace
 * down to a pure XTA trace and delegates the SMT-based feasibility check to an
 * {@link ExprTraceChecker}. If the trace is spurious (infeasible), it uses the resulting
 * refutation (e.g., interpolants) to refine the given precision.
 * <p>
 * The precision type ({@code P}) can be arbitrary. The logic for translating a refutation
 * into a precision is abstracted by the {@link RefutationToPrec} interface.
 *
 * @param <S>     The inner data state type of the XTA (must extend {@link ExprState}
 *                so the SMT-based trace checker can evaluate its formulas).
 * @param <prodS> The state type of the product DFA (representing the learned hypothesis).
 * @param <P>     The precision type used by the underlying analysis (e.g., {@code ExplPrec}).
 * @param <R>     The refutation type generated by the trace checker (e.g., {@code ItpRefutation}).
 */
public class DiscreteCompositionRefiner<S extends ExprState, prodS, P extends Prec, R extends Refutation>
        implements Refiner<DiscreteCompositionState<S, prodS>, XtaAction, P> {

    private final ExprTraceChecker<R> traceChecker;
    private final RefutationToPrec<P, R> refToPrec;
    private final PruneStrategy pruneStrategy;

    private DiscreteCompositionRefiner(
            final ExprTraceChecker<R> traceChecker,
            final RefutationToPrec<P, R> refToPrec,
            final PruneStrategy pruneStrategy
    ) {
        this.traceChecker = checkNotNull(traceChecker);
        this.refToPrec    = checkNotNull(refToPrec);
        this.pruneStrategy = checkNotNull(pruneStrategy);
    }

    /**
     * General factory for creating a refiner with an arbitrary precision type {@code P}.
     *
     * @param traceChecker  The SMT-based trace checker used to evaluate trace feasibility.
     * @param refToPrec     The strategy for converting a refutation into precision.
     * @param pruneStrategy The strategy determining how the ARG should be pruned upon refinement
     *                      (e.g., {@link PruneStrategy#LAZY} or {@link PruneStrategy#FULL}).
     * @param <S>           The inner data state type.
     * @param <prodS>       The state type of the product DFA.
     * @param <P>           The precision type.
     * @param <R>           The refutation type.
     * @return A new {@link DiscreteCompositionRefiner} instance.
     */
    public static <S extends ExprState, prodS, P extends Prec, R extends Refutation>
    DiscreteCompositionRefiner<S, prodS, P, R> create(
            ExprTraceChecker<R> traceChecker,
            RefutationToPrec<P, R> refToPrec,
            PruneStrategy pruneStrategy) {
        return new DiscreteCompositionRefiner<>(traceChecker, refToPrec, pruneStrategy);
    }

    /**
     * Convenience factory for creating a refiner directly from a {@link TraceCheckerStrategy}.
     *
     * @param strategy      The strategy bundling the trace checker and precision converter.
     * @param pruneStrategy The strategy determining how the ARG should be pruned.
     * @param <S>           The inner data state type.
     * @param <prodS>       The state type of the product DFA.
     * @param <P>           The precision type.
     * @param <R>           The refutation type.
     * @return A new {@link DiscreteCompositionRefiner} instance.
     */
    public static <S extends ExprState, prodS, P extends Prec, R extends Refutation>
    DiscreteCompositionRefiner<S, prodS, ?, R> createFromStrategy(
            TraceCheckerStrategy<P, R> strategy,
            PruneStrategy pruneStrategy) {
        return new DiscreteCompositionRefiner<>(
                strategy.checker(), strategy.refToPrec(), pruneStrategy);
    }

    @Override
    public RefinerResult<DiscreteCompositionState<S, prodS>, XtaAction, P> refine(
            final ARG<DiscreteCompositionState<S, prodS>, XtaAction> arg, final P prec) {
        checkNotNull(arg);
        checkNotNull(prec);
        assert !arg.isSafe() : "ARG must be unsafe when the refiner is called";

        final ArgTrace<DiscreteCompositionState<S, prodS>, XtaAction> cex =
                arg.getCexs().findFirst()
                   .orElseThrow(() -> new AssertionError("No counterexample in unsafe ARG"));

        final Trace<DiscreteCompositionState<S, prodS>, XtaAction> fullTrace = cex.toTrace();

        final Trace<XtaState<S>, XtaAction> xtaTrace = projectToXtaTrace(fullTrace);

        final ExprTraceStatus<R> status = traceChecker.check(xtaTrace);

        if (status.isFeasible()) {
            return RefinerResult.unsafe(fullTrace);
        }

        final R refutation = status.asInfeasible().getRefutation();

        P refinedPrec = prec;
        for (int i = 0; i < fullTrace.getStates().size(); i++) {
            refinedPrec = refToPrec.join(refinedPrec, refToPrec.toPrec(refutation, i));
        }

        if (refinedPrec.equals(prec)) {
            return RefinerResult.unsafe(fullTrace);
        }

        final ArgNode<DiscreteCompositionState<S, prodS>, XtaAction> nodeToPrune =
                cex.node(refutation.getPruneIndex());
        switch (pruneStrategy) {
            case LAZY -> arg.prune(nodeToPrune);
            case FULL -> arg.pruneAll();
        }

        return RefinerResult.spurious(refinedPrec);
    }


    private Trace<XtaState<S>, XtaAction> projectToXtaTrace(
            final Trace<DiscreteCompositionState<S, prodS>, XtaAction> trace) {
        final List<XtaState<S>> xtaStates = trace.getStates().stream()
                .map(DiscreteCompositionState::getXtaState)
                .collect(Collectors.toList());
        return Trace.of(xtaStates, trace.getActions());
    }
}